#!/bin/bash
# Generate $CATAPULT_BUILD_DIR/AppIcon.icns.
#
# Three sources, in order of priority:
#   1. If $CATAPULT_BUILD_DIR/AppIcon.icns already exists, do nothing.
#   2. If $CATAPULT_BUILD_ICON_COMMAND is set, run it and expect it to
#      produce $CATAPULT_BUILD_DIR/AppIcon.icns. (Use this for apps that
#      render their icon programmatically, e.g. from an SF Symbol via
#      a Swift script.)
#   3. Otherwise, sips/iconutil from $CATAPULT_BUILD_ICON (a single PNG).

set -e

: "${CATAPULT_BUILD_DIR:?}"
mkdir -p "$CATAPULT_BUILD_DIR"

OUT="$CATAPULT_BUILD_DIR/AppIcon.icns"

if [ -f "$OUT" ]; then
    echo "ℹ️  $OUT already exists, skipping"
    exit 0
fi

if [ -n "${CATAPULT_BUILD_ICON_COMMAND:-}" ]; then
    echo "🎨 Running icon command: $CATAPULT_BUILD_ICON_COMMAND"
    eval "$CATAPULT_BUILD_ICON_COMMAND"
    if [ ! -f "$OUT" ]; then
        echo "❌ icon command did not produce $OUT"
        exit 1
    fi
    echo "✅ AppIcon.icns generated by custom command"
    exit 0
fi

: "${CATAPULT_BUILD_ICON:?}"
if [ ! -f "$CATAPULT_BUILD_ICON" ]; then
    echo "❌ Icon source not found: $CATAPULT_BUILD_ICON"
    echo "   Set [build] icon = \"path/to/AppIcon.png\" or [build] icon_command = \"...\""
    exit 1
fi

ICONSET="$CATAPULT_BUILD_DIR/icon.iconset"
mkdir -p "$ICONSET"

sips -z 16 16     "$CATAPULT_BUILD_ICON" --out "$ICONSET/icon_16x16.png"
sips -z 32 32     "$CATAPULT_BUILD_ICON" --out "$ICONSET/icon_16x16@2x.png"
sips -z 32 32     "$CATAPULT_BUILD_ICON" --out "$ICONSET/icon_32x32.png"
sips -z 64 64     "$CATAPULT_BUILD_ICON" --out "$ICONSET/icon_32x32@2x.png"
sips -z 128 128   "$CATAPULT_BUILD_ICON" --out "$ICONSET/icon_128x128.png"
sips -z 256 256   "$CATAPULT_BUILD_ICON" --out "$ICONSET/icon_128x128@2x.png"
sips -z 256 256   "$CATAPULT_BUILD_ICON" --out "$ICONSET/icon_256x256.png"
sips -z 512 512   "$CATAPULT_BUILD_ICON" --out "$ICONSET/icon_256x256@2x.png"
sips -z 512 512   "$CATAPULT_BUILD_ICON" --out "$ICONSET/icon_512x512.png"
sips -z 1024 1024 "$CATAPULT_BUILD_ICON" --out "$ICONSET/icon_512x512@2x.png"

iconutil -c icns "$ICONSET" -o "$OUT"
echo "✅ AppIcon.icns generated"
